### ISSUE TITLE
Add governance query to get vote tally with no validator delegation

### ISSUE THREAD

**Issue by sunnya97** [osmosis-labs/cosmos-sdk#53]
## Summary

A useful metric to see what the tally would be just with validator votes only counting with self-delegation, not including delegator voting power.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
True, however, lemme tell ya a story....

Notional Labs deleages to `jabbey` -- heavily.

If we hadn't, he'd have fallen out of the active set while doing some pretty incredible research work to shorten the epoch time.  I've talked about our high level of self-bonded stake, but since we kicked that in, it's really no longer the case. I know that Nosnodes has also delegated to jabbey, same reason.
